events {
    worker_connections 2048;
    use epoll;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format quic '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" "$http3"';

    access_log /var/log/nginx/access.log quic;
    error_log /var/log/nginx/error.log warn;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Otimizacoes de buffer para transferencias massivas
    client_max_body_size 2000M;
    client_body_buffer_size 128k;

    # Configuracao TLS 1.3
    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_early_data on; # 0-RTT support
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets on;

    server {
        # Porta 443 para TCP (HTTP/1.1 e HTTP/2)
        listen 443 ssl;
        http2 on;

        # Porta 443 para UDP (HTTP/3 - QUIC)
        listen 443 quic reuseport;

        server_name server localhost 172.28.0.10;
        root /var/www/html;

        # Anuncio do servico HTTP/3 via cabecalho Alt-Svc
        add_header Alt-Svc 'h3=":443"; ma=86400' always;
        add_header X-Protocol $server_protocol always;

        # Rota de healthcheck simples
        location /health {
            return 200 'OK - Server Running';
            add_header Content-Type text/plain;
        }

        # Servir os dados estaticos
        location / {
            autoindex on;
            sendfile_max_chunk 1m;
            try_files $uri $uri/ =404;
        }
    }
}
